#+title: Crabmacs
#+author: Joar von Arndt
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
* What is Crabmacs?
Crabmacs is originally my own configuration for GNU Emacs that I've manually tinkiered with to improve my workflow, now turned into a fully fledged system in order to make it more usable to others and give me an excuse for polishing it up.

A lot of inspiration is taken from preëxisting GNU Emacs configurations, most notably:
- [[https://github.com/snackon/Witchmacs][Witchmacs]]
- [[https://github.com/doomemacs/doomemacs][Doom Emacs]]
- [[https://seagle0128.github.io/.emacs.d/][Centaur Emacs]]
- [[https://github.com/rougier/nano-emacs][N Λ N O - Emacs]]

As well as minor details from other people and their documentation scattered across the Blogosphere.
The origin for the name should be fairly obvious. 
* Configuration

Removes an error message that shows on startup.
#+BEGIN_SRC elisp
  (setq byte-compile-warnings '(cl-functions))
#+END_SRC

Sets up various packages and melpa as a repo.
#+BEGIN_SRC elisp
  (use-package openwith)
  (use-package latex-pretty-symbols)
  (use-package pretty-mode)
  (global-pretty-mode t)
  (use-package csharp-mode)
  (use-package magit)
  (use-package git-commit)
  (use-package org-agenda)
  (use-package org-roam)
  (use-package autothemer      
    :ensure t)

#+END_SRC

Disables certain visual elements on startup as well as use doom-themes.
#+BEGIN_SRC elisp
  (when (< emacs-major-version 27) (package-initialize))
  (use-package doom-themes)
  (scroll-bar-mode -1)
  (tool-bar-mode -1)
  (setq inhibit-startup-screen t)
#+END_SRC

Adds line numbers for various major modes.
#+BEGIN_SRC elisp
  (add-hook 'csharp-mode-hook 'linum-mode t)
  (add-hook 'emacs-lisp-mode-hook 'linum-mode t)
#+END_SRC

Configures the all-important emacs dashboard that shows up on startup 
#+BEGIN_SRC elisp
  (use-package dashboard
    :ensure t)
  (dashboard-setup-startup-hook)
  (setq dashboard-banner-logo-title "Gnu Emacs")
  (setq dashboard-center-content 'middle)
  (setq dashboard-startup-banner "~/Pictures/xemacs_red.svg")
  (setq compilation-ask-about-save nil)
  (setq dashboard-show-shortcuts nil)
  (setq dashboard-items nil)
  (setq dashboard-set-navigator nil)
  (setq dashboard-set-init-info nil)
  (setq dashboard-set-footer nil)
#+END_SRC

Code completion using company
#+BEGIN_SRC elisp
  (use-package company
    :init
    :ensure t
    (global-company-mode))
  (use-package company-org-block
  :ensure t
  :custom
  (company-org-block-edit-style 'prompt)
  :hook ((org-mode . (lambda ()
                       (setq-local company-backends '(company-org-block))
                       (company-mode +1)))))
#+END_SRC

Configures Org-mode to make it more attractive and useable.
#+BEGIN_SRC elisp
    (use-package emacs
      :init
      :ensure t
      (setq completion-cycle-threshold 3)
      (setq tab-always-indent 'complete))

    (with-eval-after-load 'org
      (setq org-format-latex-options
            (plist-put org-format-latex-options
                       :scale 1.3
                       ))
      (setq org-format-latex-options
            (plist-put org-format-latex-options
                       :html-scale 3
                       ))
      (setq org-startup-indented t)
      (setq prettify-symbols-mode t)
      (add-hook 'org-mode-hook 'visual-line-mode)
      (setq org-toggle-pretty-entities t)
#+END_SRC

#+BEGIN_SRC elisp
      (defun fd-switch-dictionary()
        (interactive)
        (let* ((dic ispell-current-dictionary)
               (change-major-mode-hook (if (string= dic "svenska") "english" "svenska")))
          (ispell-change-dictionary change-major-mode-hook)
          (message "Dictionary switched from %s to %s" dic change)
          ))
      )
    (global-set-key (kbd "<f8>")   'fd-switch-dictionary)
    (font-lock-add-keywords 'org-mode
                            '(("^ *\\([-]\\) "
                               (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))
    (use-package org-bullets
      :config
      (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1))))
#+END_SRC

Improves the dired experience to be better. Take that n³ and midnight commander!
#+BEGIN_SRC elisp
    (openwith-mode t)
    (setq openwith-associations (list
                                 (list (openwith-make-extension-regexp
                                        '("png" "jpg" "jpeg")) "eog" '(file))
                                 (list (openwith-make-extension-regexp
                                        '("mkv" "mp4")) "mpv" '(file))
                                 '("\\.pdf'" "evince" (file))
                                 ))
    (setq dired-listing-switches "-aBhl  --group-directories-first")
  #+END_SRC

Sets up electric pairs to make writing certain things faster and easier.
  #+BEGIN_SRC elisp
    (setq electric-pair-pairs '(
                                (?\{ . ?\})
                                (?\( . ?\))
                                (?\[ . ?\])
                                (?\" . ?\")
                                (?\$ . ?\$)
                                ))
    (electric-pair-mode t)
#+END_SRC

Enable mouse use when running Emacs in the terminal.
#+BEGIN_SRC elisp
  (xterm-mouse-mode)
#+END_SRC

